// Auto-generated file - DO NOT EDIT MANUALLY
// Generated on 2025-05-27T07:53:46.278Z

export const ANIMATED_DIGIMON = [
  "Aegisdramon",
  "AeroVeedramon",
  "Agumon",
  "Agumon (2006)",
  "Agumon (Blk)",
  "Agumon X",
  "Agumon X (Blk)",
  "Agumon YnK",
  "Airdramon",
  "Algomon Adult",
  "Algomon Baby I",
  "Algomon Baby II",
  "Algomon Child",
  "Algomon Ultimate",
  "Allomon X",
  "Alphamon",
  "Alphamon Ouryuken",
  "Alraumon",
  "AncientBeatmon",
  "AncientMegatheriumon",
  "AncientMermaimon",
  "AncientSphinxmon",
  "Andromon",
  "Angemon",
  "Angewomon",
  "Angewomon X",
  "Anomalocarimon",
  "Anomalocarimon X",
  "Antylamon",
  "Antylamon (Virus)",
  "Apocalymon",
  "Apollomon",
  "Arcadiamon In-Tr",
  "Arcadiamon Rookie",
  "Archnemon",
  "Armadillomon",
  "Armageddemon",
  "Astamon",
  "Asuramon",
  "AtlurKabuterimon (Blue)",
  "AtlurKabuterimon (Red)",
  "AxeKnightmon",
  "AxeKnightmon X",
  "Baalmon",
  "Baboongamon",
  "Babydmon",
  "Bagramon",
  "Bakemon",
  "Bakumon",
  "BanchoLeomon",
  "BanchoLilimon",
  "BanchoMamemon",
  "Barbamon",
  "Barbamon X",
  "Bearmon",
  "BeelStarmon X",
  "Beelzemon",
  "Beelzemon BM",
  "Beelzemon X",
  "Belphemon RM",
  "Belphemon X",
  "Beowolfmon",
  "Bibimon",
  "BigMamemon",
  "Birdramon",
  "Bitmon",
  "Biyomon",
  "BlackGaogamon",
  "BlackGargomon",
  "BlackGatomon",
  "BlackGrowlmon",
  "BlackGuilmon",
  "BlackKingNumemon",
  "BlackMachGaogamon",
  "BlackMegaloGrowlmon",
  "BlackRapidmon",
  "BlackSaintGargomon",
  "BlackSeraphimon",
  "BlackWarGreymon",
  "BlackWarGreymon X",
  "BlitzGreymon",
  "BloomLordmon",
  "Blossomon",
  "BlueMeramon",
  "Boltmon",
  "Bombmon",
  "Bommon",
  "Boutmon",
  "Bryweludramon",
  "Budmon",
  "Bulucomon",
  "Burgermon Mama",
  "Burgermon Papa",
  "Candmon",
  "CannonBeemon",
  "Caprimon",
  "CatchMamemon",
  "Caturamon",
  "Centalmon",
  "Cerberusmon X",
  "Chamblemon",
  "Chaosdramon",
  "Chaosdramon V2",
  "Chaosdramon X",
  "ChaosDukemon",
  "ChaosDukemon Core",
  "Chaosmon",
  "Chibickmon",
  "Chibimon",
  "Chicchimon",
  "Chicomon",
  "Chimairamon",
  "Chocomon",
  "ChoHakkaimon",
  "Choromon",
  "ClearAgumon",
  "Clockmon",
  "Cocomon",
  "Coelamon",
  "Commandramon",
  "Coronamon",
  "Cotsucomon",
  "Craniamon",
  "Craniamon X",
  "Creepymon",
  "Creepymon X",
  "Crescemon",
  "CresGarurumon",
  "Crowmon",
  "Crowmon (2006)",
  "Crusadermon X",
  "CrysPaledramon",
  "Cthyllamon",
  "Cupimon",
  "Curimon",
  "Cyberdramon",
  "Cyberdramon X",
  "Cyclonemon",
  "Dagomon",
  "Damemon",
  "Darkdramon",
  "DarknessBagramon",
  "DarkSuperstarmon",
  "DarkTyranomon X",
  "Death-X-DORUgamon",
  "DeathMeramon",
  "Deathmon",
  "Deathmon (Blk)",
  "DemiDevimon",
  "Deramon",
  "Devimon",
  "Diaboromon",
  "Diaboromon X",
  "Dianamon",
  "Diginorimon",
  "Digitamamon",
  "Dinohumon",
  "Dinorexmon",
  "Dinotigermon",
  "Dobermon",
  "Dodomon",
  "Dogmon",
  "Dokimon",
  "Dokugumon",
  "Dokunemon",
  "Dorimon",
  "Dorugamon",
  "Dorugoramon",
  "DoruGreymon",
  "Dorumon",
  "Dracmon",
  "Dracomon X",
  "Drimogemon",
  "Duramon",
  "Duskmon",
  "Dynasmon X",
  "Ebemon",
  "Ebemon X",
  "Ebidramon",
  "Ekakimon",
  "Elecmon",
  "Elecmon (Violet)",
  "Entmon",
  "Etemon",
  "Examon X",
  "ExVeemon",
  "ExVeemon (Blk)",
  "Fanbeemon",
  "Filmon",
  "Firamon",
  "Flaremon",
  "Floramon",
  "Frigimon",
  "Fufumon",
  "Fugamon",
  "Gabumon X",
  "Gaioumon",
  "Gallantmon",
  "Gallantmon X",
  "Gammamon",
  "Ganimon",
  "Gankoomon",
  "Gankoomon X",
  "GaoGamon",
  "Gaomon",
  "Garbagemon",
  "Gargomon",
  "Garudamon",
  "Garudamon X",
  "Garurumon",
  "Garurumon (Blk)",
  "Gatomon",
  "Gatomon X",
  "Gawappamon",
  "Gazimon",
  "Gazimon X",
  "Gekomon",
  "GeoGreymon",
  "Geremon",
  "Gesomon",
  "Ghostmon",
  "Gigadramon",
  "GigaSeadramon",
  "Gigimon",
  "Ginryumon",
  "Giromon",
  "Gizamon",
  "Gogmamon",
  "Gokimon",
  "Gokumon",
  "GoldNumemon",
  "Goldramon X",
  "GoldVeedramon",
  "Gomamon",
  "Gomamon X",
  "Goromon",
  "Gotsumon",
  "GraceNovamon",
  "Grademon",
  "GrandDracmon",
  "GrandisKuwagamon",
  "GrandLocomon",
  "GrapLeomon",
  "GreatKingScumon",
  "Greymon",
  "Greymon (2010)",
  "Greymon (Blue)",
  "Greymon X",
  "Growlmon",
  "Growlmon (Orange)",
  "Growlmon X",
  "Gryphonmon",
  "Gryzmon",
  "Guardromon",
  "Guardromon (Gold)",
  "Guilmon",
  "Guilmon X",
  "Gummymon",
  "Gundramon",
  "Gururumon",
  "Gusokumon",
  "Hackmon",
  "Hagurumon",
  "Hangyomon",
  "Hanumon",
  "HerculesKabuterimon",
  "Herissmon",
  "Hexeblaumon",
  "HiAndromon",
  "Hisyaryumon",
  "Hiyarimon",
  "HolyAngemon",
  "HolyDigitamamon",
  "Holydramon",
  "Holydramon X",
  "Hookmon",
  "Hououmon",
  "Hououmon X",
  "Hyokomon",
  "Hyougamon",
  "IceDevimon",
  "Icemon",
  "Igamon",
  "Ikkakumon",
  "Imperialdramon FM",
  "Imperialdramon FM (Blk)",
  "Imperialdramon PM",
  "Impmon",
  "Impmon X",
  "Insekimon",
  "Jazamon",
  "Jazardmon",
  "Jazarichmon",
  "Jesmon",
  "Jesmon GX",
  "Jesmon X",
  "Junkmon",
  "Justimon X",
  "Jyagamon",
  "Jyarimon",
  "Jyureimon",
  "Kabuterimon",
  "KaiserGreymon",
  "KaiserLeomon",
  "Kakkinmon",
  "KaratsukiNumemon",
  "Kazuchimon",
  "Kentaurosmon X",
  "Keramon",
  "Keramon X",
  "Kerpymon (Evil)",
  "Kerpymon (Evil) X",
  "Kerpymon (Good)",
  "Kerpymon (Good) X",
  "Ketomon",
  "Kiimon",
  "KingEtemon",
  "Kiwimon",
  "Knightmon",
  "Koemon",
  "Kokabuterimon",
  "Kokuwamon",
  "Kokuwamon X",
  "Koromon",
  "Kougamon",
  "Kozenimon",
  "Kunemon",
  "Kuramon",
  "Kuwagamon",
  "Kuwagamon X",
  "Kuzuhamon",
  "Kyokyomon",
  "Kyubimon",
  "Kyubimon (Silver)",
  "Labramon",
  "LadyDevimon",
  "LadyDevimon X",
  "Lalamon",
  "Lavogaritamon",
  "Lavorvomon",
  "Leafmon",
  "Lekismon",
  "Leomon",
  "Leomon X",
  "Leopardmon",
  "Leopardmon X",
  "Leviamon",
  "Leviamon X",
  "Lilamon",
  "Lilithmon",
  "Lilithmon X",
  "Lillymon",
  "Lillymon X",
  "Lopmon",
  "Lopmon X",
  "Lotosmon",
  "Lucemon",
  "Lucemon FM",
  "Lucemon SM",
  "Lucemon X",
  "Ludomon",
  "Lunamon",
  "Lynxmon",
  "MachGaogamon",
  "Machinedramon",
  "MadLeomon",
  "Magnamon X",
  "MaloMyotismon",
  "Mamemon",
  "Mamemon X",
  "Mametyramon",
  "Mammon",
  "Mammon X",
  "Manbomon",
  "Mantaraymon X",
  "Manticoremon",
  "MarineAngemon",
  "MarineChimairamon",
  "MarineDevimon",
  "Mastemon",
  "Mechanorimon",
  "Megadramon",
  "MegaSeadramon",
  "MegaSeadramon X",
  "Megidramon",
  "Megidramon X",
  "MeicooBaby",
  "MeicooChild",
  "Meicoomon",
  "Meicrackmon",
  "Meicrackmon VM",
  "Mephistomon",
  "Mephistomon X",
  "Meramon",
  "Meramon X",
  "Mermaimon",
  "MetalEtemon",
  "MetalGarurumon",
  "MetalGarurumon (Blk)",
  "MetalGarurumon X",
  "MetalGreymon",
  "MetalGreymon (Blue)",
  "MetalGreymon X",
  "MetalGreymon X (Blue)",
  "Metallicdramon",
  "MetalMamemon",
  "MetalMamemon X",
  "MetalPhantomon",
  "MetalPiranimon",
  "MetalSeadramon",
  "MetalTyrannomon",
  "MetalTyrannomon V2",
  "MetalTyrannomon X",
  "Mikemon",
  "Millenniumon",
  "Mimicmon",
  "Minervamon X",
  "Minomon",
  "Mochimon",
  "Mokumon",
  "Monimon",
  "Monochromon",
  "Monochromon X",
  "Monzaemon",
  "Monzaemon X",
  "Moonmon",
  "MoriShellmon",
  "Morphomon",
  "Muchomon",
  "MudFrigimon",
  "Mushroomon",
  "Myotismon",
  "Myotismon X",
  "Nanomon",
  "Nefertimon X",
  "NeoDevimon",
  "NiseDrimogemon",
  "NoblePumpkinmon",
  "Numemon",
  "Numemon X",
  "Nyaromon",
  "Nyokimon",
  "Ogremon",
  "Ogremon X",
  "Ogudomon",
  "Ogudomon X",
  "Okuwamon",
  "Okuwamon X",
  "Omekamon",
  "Omnimon",
  "Omnimon Alter-S",
  "Omnimon X",
  "Omnimon Zwart",
  "OmniShoutmon X",
  "Ophanimon",
  "Ophanimon Core",
  "Ophanimon FM X",
  "Ophanimon X",
  "Ordinemon",
  "Orochimon",
  "Otamamon",
  "Otamamon (Red)",
  "Otamamon X",
  "Ouryumon",
  "Pabumon",
  "Pafumon",
  "Pagumon",
  "Paildramon",
  "Paledramon",
  "Palmon",
  "Palmon X",
  "Pandamon",
  "Panjyamon",
  "Panjyamon X",
  "Paomon",
  "Parasaurmon",
  "Pegasusmon X",
  "Penmon",
  "PetiMeramon",
  "PetitMamon",
  "Petitmon",
  "Phantomon",
  "Phascomon",
  "Piccolomon",
  "Pickmon",
  "Pidmon",
  "Piemon",
  "Pipimon",
  "Piranimon",
  "Pitchmon",
  "PlatinumNumemon",
  "PlatinumScumon",
  "Plesiomon",
  "Plesiomon X",
  "Pokomon",
  "Popomon",
  "Porcupamon",
  "Poromon",
  "PrinceMamemon",
  "PrinceMamemon X",
  "Pteranomon X",
  "Pukamon",
  "Pukumon",
  "Pulsemon",
  "Pumpkinmon",
  "Puppetmon",
  "Pupumon",
  "Puroromon",
  "Pururumon",
  "Pusumon",
  "Pusurimon",
  "Puttimon",
  "Puyomon",
  "Pyocomon",
  "Pyonmon",
  "Rafflesimon",
  "RagnaLordmon",
  "Raguelmon",
  "Raidenmon",
  "Raihimon",
  "RaijiLudomon",
  "Rapidmon",
  "Rapidmon (Armor)",
  "Rapidmon X",
  "Raptordramon",
  "Rasenmon",
  "Rasenmon FM",
  "Rasielmon",
  "Rebellimon",
  "RedVeedramon",
  "RedVegiemon",
  "Regalecusmon",
  "Relemon",
  "Renamon",
  "Renamon X",
  "Reppamon",
  "Rhinomon",
  "Rhinomon X",
  "RizeGreymon",
  "RizeGreymon X",
  "Rosemon",
  "Rosemon BM",
  "Rosemon X",
  "Rukamon",
  "RustTyrannomon",
  "Ryudamon",
  "Saberdramon",
  "SaberLeomon",
  "Sagomon",
  "SaintGargomon",
  "Sakuyamon",
  "Sakuyamon X",
  "Salamon",
  "Salamon X",
  "SandYanmamon",
  "Sangloupmon",
  "Sangomon",
  "SaviorHackmon",
  "Scorpiomon",
  "Scumon",
  "Seadramon",
  "Seadramon X",
  "Seraphimon",
  "Shadramon",
  "Shawujinmon",
  "Sheepmon",
  "Shellmon",
  "ShimaUnimon",
  "ShinMonzaemon",
  "Shootmon",
  "Siesamon X",
  "Sirenmon",
  "Sistermon Blanc",
  "SkullBaluchimon",
  "SkullGreymon",
  "SkullMammon",
  "SkullMammon X",
  "SnowAgumon",
  "Socerimon",
  "Solarmon",
  "Soulmon",
  "Starmon",
  "Stefilmon",
  "Submarimon",
  "Sunamon",
  "Sunarizamon",
  "Sunflowmon",
  "Sunmon",
  "SuperStarmon",
  "Susanomon",
  "Swimmon",
  "Syakomon",
  "Syakomon X",
  "Tanemon",
  "Tankmon",
  "Targetmon",
  "Tekkamon",
  "Tentomon",
  "Terriermon",
  "Terriermon X",
  "Thunderballmon",
  "TiaLudomon",
  "TigerVespamon",
  "Tinkermon",
  "Titamon",
  "Tobiumon",
  "Tobucatmon",
  "Togemon",
  "Togemon X",
  "Tokomon X",
  "TonosamaGekomon",
  "TorikaraBallmon",
  "Tortamon",
  "ToyAgumon",
  "ToyAgumon (Blk)",
  "Triceramon",
  "Triceramon X",
  "Troopmon",
  "Tsubumon",
  "Tsumemon",
  "Tsunomon",
  "Turuiemon",
  "Tylomon X",
  "Tyrannomon",
  "Tyrannomon X",
  "UlforceVeedramon",
  "UlforceVeedramon X",
  "UltimateBrachimon",
  "Upamon",
  "Vademon",
  "Valdurmon",
  "Veedramon",
  "Veedramon (Blk)",
  "Veemon",
  "Vegiemon",
  "Velgrmon",
  "VenomMyotismon",
  "Vermillimon",
  "Volcanicdramon",
  "VoltoBautamon",
  "Vorvomon",
  "Wanyamon",
  "WarGreymon",
  "WarGreymon X",
  "WarGrowlmon",
  "WarGrowlmon (Orange)",
  "WarGrowlmon X",
  "WaruMonzaemon",
  "WaruSeadramon",
  "Waspmon",
  "Weedmon",
  "WereGarurumon",
  "WereGarurumon (Blk)",
  "WereGarurumon X",
  "Whamon",
  "Wizardmon",
  "Wizardmon X",
  "Woodmon",
  "Wormmon",
  "Xiaomon",
  "Yaamon",
  "Yanmamon",
  "Youkomon",
  "YukimiBotamon",
  "Yuramon",
  "Zenimon",
  "Zerimon",
  "Zudomon",
  "Zurumon"
];
