export interface Title {
  id: number;
  name: string;
  description: string;
  category: "campaign" | "collection" | "evolution" | "battle" | "streak";
  requirement_type:
    | "campaign_stage"
    | "digimon_count"
    | "digimon_level"
    | "digimon_stage"
    | "battle_wins"
    | "longest_streak";
  requirement_value: number | string;
  tier: "bronze" | "silver" | "gold" | "platinum";
}

export const TITLES: Title[] = [
  // Campaign titles
  {
    id: 1,
    name: "Digital Rookie",
    description: "Completed Stage 10 of the Campaign",
    category: "campaign",
    requirement_type: "campaign_stage",
    requirement_value: 10,
    tier: "bronze",
  },
  {
    id: 2,
    name: "Island Explorer",
    description: "Defeated Devimon and cleansed the File Island.",
    category: "campaign",
    requirement_type: "campaign_stage",
    requirement_value: 20,
    tier: "bronze",
  },
  {
    id: 3,
    name: "Vampire Hunter",
    description: "Defeated the resurrected Myotismon.",
    category: "campaign",
    requirement_type: "campaign_stage",
    requirement_value: 30,
    tier: "silver",
  },
  {
    id: 4,
    name: "Master of the Spiral",
    description: "Conquered all four Dark Masters.",
    category: "campaign",
    requirement_type: "campaign_stage",
    requirement_value: 46,
    tier: "gold",
  },
  {
    id: 5,
    name: "DigiDestined",
    description: "Defeated the final boss, Apocalymon.",
    category: "campaign",
    requirement_type: "campaign_stage",
    requirement_value: 60,
    tier: "platinum",
  },
  {
    id: 6,
    name: "Seven Deadly Sins",
    description: "Defeated all Seven Great Demon Lords.",
    category: "campaign",
    requirement_type: "campaign_stage",
    requirement_value: 70,
    tier: "platinum",
  },
  {
    id: 7,
    name: "Royal Challenger",
    description: "Defeated and gained the trust of the Royal Knights.",
    category: "campaign",
    requirement_type: "campaign_stage",
    requirement_value: 80,
    tier: "platinum",
  },
  {
    id: 8,
    name: "Multiversal Tamer",
    description: "Survived the Space Time Distortion.",
    category: "campaign",
    requirement_type: "campaign_stage",
    requirement_value: 56,
    tier: "platinum",
  },
  // Collection titles
  {
    id: 101,
    name: "Digimon Fan",
    description: "Discovered 50 different Digimon",
    category: "collection",
    requirement_type: "digimon_count",
    requirement_value: 50,
    tier: "bronze",
  },
  {
    id: 102,
    name: "Digimon Researcher",
    description: "Discovered 100 different Digimon",
    category: "collection",
    requirement_type: "digimon_count",
    requirement_value: 100,
    tier: "silver",
  },
  {
    id: 103,
    name: "Digimon Professor",
    description: "Discovered 200 different Digimon",
    category: "collection",
    requirement_type: "digimon_count",
    requirement_value: 200,
    tier: "gold",
  },
  {
    id: 104,
    name: "Digimon Master",
    description: "Discovered 300 different Digimon",
    category: "collection",
    requirement_type: "digimon_count",
    requirement_value: 300,
    tier: "platinum",
  },
  {
    id: 105,
    name: "Digimon Legend",
    description: "Discovered every single Digimon",
    category: "collection",
    requirement_type: "digimon_count",
    requirement_value: 362,
    tier: "platinum",
  },
  // Evolution titles
  {
    id: 201,
    name: "Ultimate Tamer",
    description: "Evolved a Digimon to Ultimate stage",
    category: "evolution",
    requirement_type: "digimon_stage",
    requirement_value: "Ultimate",
    tier: "silver",
  },
  {
    id: 202,
    name: "Mega Tamer",
    description: "Evolved a Digimon to Mega stage",
    category: "evolution",
    requirement_type: "digimon_stage",
    requirement_value: "Mega",
    tier: "gold",
  },
  {
    id: 203,
    name: "Ultra Tamer",
    description: "Evolved a Digimon to Ultra stage",
    category: "evolution",
    requirement_type: "digimon_stage",
    requirement_value: "Ultra",
    tier: "platinum",
  },

  // Arena Battle titles
  {
    id: 301,
    name: "Battle Novice",
    description: "Won 10 arena battles.",
    category: "battle",
    requirement_type: "battle_wins",
    requirement_value: 10,
    tier: "bronze",
  },
  {
    id: 302,
    name: "Battle Expert",
    description: "Won 50 arena battles.",
    category: "battle",
    requirement_type: "battle_wins",
    requirement_value: 50,
    tier: "silver",
  },
  {
    id: 303,
    name: "Battle Master",
    description: "Won 200 team battles.",
    category: "battle",
    requirement_type: "battle_wins",
    requirement_value: 200,
    tier: "gold",
  },
  {
    id: 304,
    name: "Battle Champion",
    description: "Won 1000 arena battles.",
    category: "battle",
    requirement_type: "battle_wins",
    requirement_value: 1000,
    tier: "platinum",
  },

  // Streak titles
  {
    id: 400,
    name: "Getting Started",
    description: "Completed 1 Daily Quota.",
    category: "streak",
    requirement_type: "longest_streak",
    requirement_value: 1,
    tier: "bronze",
  },
  {
    id: 401,
    name: "In Training",
    description: "Maintained a 3 day streak.",
    category: "streak",
    requirement_type: "longest_streak",
    requirement_value: 3,
    tier: "bronze",
  },
  {
    id: 402,
    name: "Routine Rookie",
    description: "Maintained a 7 day streak.",
    category: "streak",
    requirement_type: "longest_streak",
    requirement_value: 7,
    tier: "silver",
  },
  {
    id: 403,
    name: "Champion Flow",
    description: "Maintained a 14 day streak.",
    category: "streak",
    requirement_type: "longest_streak",
    requirement_value: 14,
    tier: "silver",
  },
  {
    id: 404,
    name: "Ultimate Bond",
    description: "Maintained a 31 day streak.",
    category: "streak",
    requirement_type: "longest_streak",
    requirement_value: 31,
    tier: "gold",
  },
  {
    id: 405,
    name: "Crest Ignited",
    description: "Maintained a 50 day streak.",
    category: "streak",
    requirement_type: "longest_streak",
    requirement_value: 50,
    tier: "gold",
  },
  {
    id: 406,
    name: "Digivolved",
    description: "Maintained a 75 day streak.",
    category: "streak",
    requirement_type: "longest_streak",
    requirement_value: 75,
    tier: "gold",
  },
  {
    id: 407,
    name: "Perfect Partner",
    description: "Maintained a 100 day streak.",
    category: "streak",
    requirement_type: "longest_streak",
    requirement_value: 100,
    tier: "platinum",
  },
  {
    id: 408,
    name: "Digitask Adventure",
    description: "Maintained a 365 day streak. One full year!",
    category: "streak",
    requirement_type: "longest_streak",
    requirement_value: 365,
    tier: "platinum",
  },
];
